# Generated by Django 3.1.4 on 2020-12-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticket_pid', models.IntegerField()),
                ('number', models.CharField(default='', max_length=200)),
                ('user_email_id', models.IntegerField()),
                ('dept_id', models.IntegerField()),
                ('sla_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('staff_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('email_id', models.IntegerField()),
                ('lock_id', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('ip_address', models.CharField(default='', max_length=40)),
                ('source', models.IntegerField(choices=[(0, 'Web'), (1, 'Email'), (2, 'Phone'), (3, 'API'), (4, 'Other')], null=True)),
                ('source_extra', models.CharField(default='', max_length=40)),
                ('isoverdue', models.SmallIntegerField(null=True)),
                ('isanswered', models.SmallIntegerField(null=True)),
                ('duedate', models.DateTimeField()),
                ('est_duedate', models.DateTimeField()),
                ('reopened', models.DateTimeField()),
                ('closed', models.DateTimeField()),
                ('lastupdate', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'ost_ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ticket_status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('state', models.CharField(default='', max_length=16)),
                ('mode', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('properties', models.TextField(max_length=65535)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'ost_ticket_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('name', models.CharField(default='', max_length=128)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'ost_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=128)),
                ('status', models.IntegerField()),
                ('timezone', models.CharField(default='', max_length=64)),
                ('lang', models.CharField(default='', max_length=64)),
                ('username', models.CharField(default='', max_length=64)),
                ('passwd', models.CharField(default='', max_length=128)),
                ('backend', models.CharField(default='', max_length=32)),
                ('extra', models.TextField(max_length=65535)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ost_user_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_email',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('address', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'ost_user_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='help_topic',
            fields=[
                ('topic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_pid', models.IntegerField()),
                ('ispublic', models.SmallIntegerField()),
                ('noautoresp', models.SmallIntegerField()),
                ('flags', models.IntegerField()),
                ('status_id', models.IntegerField()),
                ('priority_id', models.IntegerField()),
                ('dept_id', models.IntegerField()),
                ('staff_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('sla_id', models.IntegerField()),
                ('page_id', models.IntegerField()),
                ('sequence_id', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('topic', models.CharField(max_length=32)),
                ('number_format', models.CharField(max_length=32)),
                ('notes', models.TextField(max_length=65535)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
