# Generated by Django 3.1.4 on 2021-02-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_auto_20210211_1110'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='help_topic',
            table='ost_help_topic',
        ),
    ]
